INSERT INTO `test3fanfiction_pagelinks` (`link_id`, `link_name`, `link_text`, `link_url`, `link_target`, `link_access`) VALUES (1, 'home', 'Home', 'index.php', '0', 0),
(2, 'recent', 'Most Recent', 'browse.php?type=recent', '0', 0),
(3, 'login', 'Login', 'user.php?action=login', '0', 0),
(4, 'adminarea', 'Admin', 'admin.php', '0', 2),
(5, 'logout', 'Logout', 'user.php?action=logout', '0', 1),
(6, 'featured', 'Featured Stories', 'browse.php?type=featured', '0', 0),
(7, 'catslink', 'Categories', 'browse.php?type=categories', '0', 0),
(8, 'members', 'Members', 'authors.php?action=list', '0', 0),
(9, 'authors', 'Authors', 'authors.php?list=authors', '0', 0),
(10, 'help', 'Help', 'viewpage.php?page=help', '0', 0),
(11, 'search', 'Search', 'search.php', '0', 0),
(12, 'series', 'Series', 'browse.php?type=series', '0', 0),
(13, 'tens', 'Top Tens', 'toplists.php', '0', 0),
(14, 'challenges', 'Challenges', 'browse.php?type=challenges', '0', 0),
(15, 'contactus', 'Contact Us', 'contact.php', '0', 0),
(16, 'rules', 'Rules', 'viewpage.php?page=rules', '0', 0),
(17, 'tos', 'Terms of Service', 'viewpage.php?page=tos', '0', 0),
(18, 'rss', '<img src=''images/xml.gif'' alt=''RSS'' border=''0''>', 'rss.php', '0', 0),
(19, 'login', 'Account Info', 'user.php', '0', 1),
(20, 'titles', 'Titles', 'browse.php?type=titles', '0', 0),
(21, 'register', 'Register', 'user.php?action=register', '0', 0),
(22, 'lostpassword', 'Lost Password', 'user.php?action=lostpassword', '0', 0),
(23, 'newsarchive', 'News Archive', 'news.php', '0', 0),
(24, 'browse', 'Browse', 'browse.php', '0', 0),
(25, 'charslink', 'Characters', 'browse.php?type=characters', '0', 0),
(26, 'ratings', 'Ratings', 'browse.php?type=ratings', '0', 0);
