INSERT INTO `fanfiction_panels` (`panel_name`, `panel_title`, `panel_url`, `panel_level`, `panel_order`, `panel_hidden`, `panel_type`) VALUES (1, 'submitted', 'Submissions', '', 3, 5, 0, 'A'),
('versioncheck', 'Version Check', '', 3, 7, 0, 'A'),
('newstory', 'Add New Story', 'stories.php?action=newstory&admin=1', 3, 2, 0, 'A'),
('addseries', 'Add New Series', 'series.php?action=add', 3, 3, 0, 'A'),
('news', 'News', '', 3, 4, 0, 'A'),
('featured', 'Featured Stories', '', 3, 5, 0, 'A'),
('characters', 'Characters', '', 2, 1, 0, 'A'),
('ratings', 'Ratings', '', 2, 2, 0, 'A'),
('members', 'Members', '', 2, 3, 0, 'A'),
('mailusers', 'Mail Users', '', 2, 4, 0, 'A'),
('settings', 'Settings', '', 1, 1, 0, 'A'),
('blocks', 'Blocks', '', 1, 6, 0, 'A'),
('censor', 'Censor', '', 1, 0, 1, 'A'),
('admins', 'Admins', '', 1, 5, 0, 'A'),
('classifications', 'Classifications', '', 2, 5, 0, 'A'),
('categories', 'Categories', '', 2, 6, 0, 'A'),
('custpages', 'Custom Pages', '', 1, 4, 0, 'A'),
('validate', 'Validate Submission', '', 3, 0, 1, 'A'),
('yesletter', 'Validation Letter', '', 3, 0, 1, 'A'),
('noletter', 'Rejection Letter', '', 3, 0, 1, 'A'),
('links', 'Page Links', '', 1, 3, 0, 'A'),
('messages', 'Message Settings', '', 2, 0, 1, 'A'),
('login', 'Login', '', 0, 0, 1, 'U'),
('logout', 'Logout', '', 1, 1, 0, 'U'),
('revreceived', 'Reviews Received', '', 1, 0, 1, 'U'),
('editprefs', 'Edit Preferences', '', 1, 2, 0, 'U'),
('lostpassword', 'Lost Password', '', 0, 0, 1, 'U'),
('editbio', 'Edit Bio', '', 1, 3, 0, 'U'),
('register', 'Register', '', 0, 0, 1, 'U'),
('manageimages', 'Manage Images', '', 1, 1, 0, 'S'),
('manfavs', 'Manage Favorites', '', 1, 4, 0, 'F'),
('revres', 'Review Response', '', 1, 0, 1, 'U'),
('stats', 'View Your Statistics', '', 1, 5, 0, 'U'),
('newstory', 'Add New Story', 'stories.php?action=newstory', 1, 2, 0, 'S'),
('newseries', 'Add New Series', 'series.php?action=add', 1, 3, 0, 'S'),
('managestories', 'Manage Stories', 'stories.php?action=viewstories', 1, 4, 0, 'S'),
('manageseries', 'Manage Series', 'series.php?action=manage', 1, 5, 0, 'S'),
('reviewsby', 'Your Reviews', '', 1, 0, 1, 'U'),
('storiesby', 'Stories', '', 0, 1, 0, 'P'),
('seriesby', 'Series', '', 0, 2, 0, 'P'),
('reviewsby', 'Reviews', '', 0, 3, 0, 'P'),
('categories', 'Categories', '', 0, 1, 0, 'B'),
('characters', 'Characters', '', 0, 2, 0, 'B'),
('ratings', 'Ratings', '', 0, 3, 0, 'B'),
('titles', 'Titles', '', 0, 4, 0, 'B'),
('class', 'Classes', '', 0, 0, 1, 'B'),
('recent', 'Most Recent', '', 0, 0, 1, 'B'),
('featured', 'Featured Stories', '', 0, 0, 1, 'B'),
('panels', 'Panels', '', 1, 2, 0, 'A'),
('phpinfo', 'PHP Info', '', 1, 7, 0, 'A'),
('contact', 'Contact', '', 0, 0, 1, 'P'),
('series', 'Series', '', 0, 5, 0, 'B'),
('viewlog', 'Action Log', '', 1, 8, 0, 'A'),
('shortstories', '10 Shortest Stories', 'toplists/default.php', 0, 1, 0, 'L'),
('longstories', '10 Longest Stories', 'toplists/default.php', 0, 2, 0, 'L'),
('largeseries', '10 Largest Series', 'toplists/default.php', 0, 3, 0, 'L'),
('smallseries', '10 Smallest Series', 'toplists/default.php', 0, 4, 0, 'L'),
('reviewedseries', '10 Most Reviewed Series', 'toplists/default.php', 0, 5, 0, 'L'),
('prolificauthors', '10 Most Prolific Authors', 'toplists/default.php', 0, 10, 0, 'L'),
('prolificreviewers', '10 Most Prolific Reviewers', 'toplists/default.php', 0, 12, 0, 'L'),
('reviewedstories', '10 Most Reviewed Stories', 'toplists/default.php', 0, 8, 0, 'L'),
('readstories', '10 Most Read Stories', 'toplists/default.php', 0, 9, 0, 'L'),
('favstories', '10 Most Favorite Stories', 'toplists/default.php', 0, 7, 0, 'L'),
('favauthors', '10 Most Favorite Authors', 'toplists/default.php', 0, 11, 0, 'L'),
('favseries', '10 Most Favorite Series', 'toplists/default.php', 0, 6, 0, 'L'),
('favst', 'Favorite Stories', '', 0, 0, 1, 'F'),
('favse', 'Favorite Series', '', 0, 0, 1, 'F'),
('favau', 'Favorite Authors', '', 0, 0, 1, 'F'),
('favst', 'Favorite Stories', '', 0, 0, 1, 'U'),
('favse', 'Favorite Series', '', 0, 0, 1, 'U'),
('favau', 'Favorite Authors', '', 0, 0, 1, 'U'),
('favlist', 'Favorites', 'viewuser.php?action=manfavs', 0, 1, 0, 'F'),
('skins', 'Skins', '', 3, 6, 0, 'A'),
('authorfields', 'Profile Information', '', 1, 9, 0, 'A'),
('manual', 'Admin Manual', '', '3', '6', '0', 'A'),
('modules', 'Modules', '', 1, '11', 0, 'A'),
('maintenance', 'Archive Maintenance', '', 1, 10, 0, 'A');

